### ISSUE TITLE
Request new software term for Goslin, the grammar on succinct lipid nomenclature

### ISSUE THREAD

**Issue by nilshoffmann** [HUPO-PSI/psi-ms-CV#163]
### What is the new software's name?

Goslin

### Describe the software briefly.

The Goslin implementations parse common lipid name dialects and normalize them to the recent lipid shorthand nomenclature based on grammars on succinct lipid nomenclature. [PMID:32589019, https://github.com/lifs-tools/goslin]

### Software type

MS:1001457 ! data processing software, MS:1002414 ! postprocessing software, MS:1002964 ! lipidomics analysis software

### Describe any additional information.

Please note that Goslin has implementations in C++, R, C#, Java and Python. I am not sure, whether we should request a child-term for each specific implementation?

**Comment by mobiusklein** [comment]
```yaml
[Term]
id: MS:1003309
name: Goslin
def: "The Goslin implementations parse common lipid name dialects and normalize them to the recent lipid shorthand nomenclature based on grammars on succinct lipid nomenclature." [PMID:32589019, https://github.com/lifs-tools/goslin]
is_a: MS:1001457 ! data processing software
is_a: MS:1002414 ! postprocessing software
is_a: MS:1002964 ! lipidomics analysis software
```

Do the different implementations provide additional features necessary to differentiate them?
